
# **Laboratorio (6%)**

**Instrucciones:** El presente trabajo consta de seis (6) problemas cada uno con un valor asignado. El profesor del curso es el encargado de calificar el trabajo, y para ello tendrá en cuenta el  procedimiento realizado (que debe mostrar el estudiante) y las respectivas respuestas a los ejercicios. Por favor, **comentar de forma organizada y coherente** los pasos realizados.


 El laboratorio **debe ser realizado en grupos, con el número máximo integrantes definido por el profesor**. Se debe entregar un solo documento por grupo, y dentro del mismo **debe aparecer de forma clara el nombre completo de todos los integrantes**.  Ver espacio a continuación.


**Formato de entrega:** Para la entrega de este trabajo, descargue el archivo en **formato PDF** (esto lo consigue con la combinación de teclas **ctrl + p** y guardando el archivo en el formato requerido) y enviarlo a través de Interactiva en el buzón designado para ello.

**NOTA:** Revisar el documento antes de enviarlo. Asegúrese de que el documento sea legible y tenga todos los procedimientos con las respuestas impresas de los cálculos realizados.

In [ ]:
########---------------Nombre completo de los integrantes del grupo de trabajo-------------------##########

# Integrante 1: Juan David Bedoya Cantór


### **Ejercicio #1: (0.8)**
Dados los siguientes vectores

\begin{equation*}
 \vec{u} = (12, 51, -1),
 \hspace{0.5cm}
 \vec{v} = (2, 11, 57),
\hspace{0.5cm}
 \vec{w} = (66, 9, 15),
 \hspace{0.5cm}
 \vec{z} = (1, 33, -8),
\end{equation*}

realizar las operaciones indicadas:

a). **(0.2)** $ (\vec{u} + \vec{z}- \vec{v}) \cdot (\vec{z}-3\vec{w} + \vec{v}).$

b). **(0.2)** $\| \vec{z}- \vec{w}\|- \|\vec{w} \times \vec{u}\|.$

c). **(0.2)** $\|\vec{u}\|(\vec{v} + \vec{z}) + \| 2\vec{z}- 3\vec{w}\|\vec{z}.$

d). **(0.2)** Hallar dos vectores $\vec{p}$ y $\vec{h}$ tales que $\vec{v} = \vec{p} + \vec{h}$ con $\vec{p}$ paralelo a $\vec{u}$ y $\vec{h}$ ortogonal a $\vec{u}$.

In [2]:
# Solución Ejercicio 1. (No olvide imprimir las respuestas de sus cálculos)

# Importar la bibliotecas numpy con el alias np y math.
import numpy as np
import math

# Definir los vectores u,v,w,z

# Definición de los vectores
u = np.array([12, 51, -1])
v = np.array([2, 11, 57])
w = np.array([66, 9, 15])
z = np.array([1, 33, -8])

# (a):
pt1_a = u + z - v
pt2_a = z - 3 * w + v
res_1a = np.dot(pt1_a, pt2_a)

# (b):
dif_1b = z - w
norma_dif = math.sqrt(np.dot(dif_1b, dif_1b))
cruz = np.cross(w, u)
norma_cruz = math.sqrt(np.dot(cruz, cruz))
res_1b = norma_dif - norma_cruz

# (c):
norma_u = math.sqrt(np.dot(u, u))
suma_vz = v + z
pt1_c = norma_u * suma_vz
combinado = 2 * z - 3 * w
norma_combinado = math.sqrt(np.dot(combinado, combinado))
pt2_c = norma_combinado * z
res_c = pt1_c + pt2_c

# (d):
k = np.dot(u, v) / np.dot(u, u)
p = k * u
h = v - p
verificacion = np.dot(u, h)

# Imprimir las respuestas
print(f"a) Resultado: {res_1a:.2f}")
print(f"b) Resultado: {res_1b:.2f}")
print(f"c) Resultado: {res_c}")
print(f"d) p (paralelo a u): {p}")
print(f"   h (ortogonal a u): {h}")
print(f"   Verificación u·h = {verificacion:.2e} (debe ser ~0)")

a) Resultado: -1168.00
b) Resultado: -3284.69
c) Resultado: [ 366.15183891 9200.8847326   896.15246064]
d) p (paralelo a u): [ 2.30735615  9.80626366 -0.19227968]
   h (ortogonal a u): [-0.30735615  1.19373634 57.19227968]
   Verificación u·h = 2.84e-14 (debe ser ~0)


### **Ejercicio #2. (1.2)**
Camilo ha decidido enviarle un mensaje codificado a Lucía a través del **método Hill**. El mensaje codificado es:

-9, 0 , -6, -8, 5, 15, 8, 4, 8, -23, 11, 12, 8, 3, -27, 7, -15, -1,  0, -6,  6,
 161, 110, 84, 82, 69, -1, 84, 104, 38, 125, 157,  82, 94, 75, 73, 43, 135,  105, 128, 26, 106, 143, 140, 56, 84, 77, 25, 102, 112, 38, 127, 175, 82,  104, 75, 43, 29, 127, 103, 128, -16, 134, -128, -108, -22, -36, -64,  0, -68, -106, 10, -94, -158, -38, -70, -40, -14, 6, -110,  -64, -72, 24, -84, 105, 76,  46,  64, 41, -7, 66,  70, 20, 93, 101, 56, 62, 37, 71, 19, 79, 69, 84, 16, 50


Para el proceso de codificacion, Camilo tuvo presente la siguiente información:

1. Llave de codificación: 0, 0, 1, -1, 0, 0, 4, -1, 1, 2, -2, 4, 1, 1, 2, 2, -4, 0, 0, -2, 0, 2, -1, 1, 2.
2. Dimensión de la matriz de codificación $5 \times 5$.

a). **(0.4)** Cree e imprima la matriz de codificación $A$, y la matriz codificada $C$.

b). **(0.4)** Cree e imprima la matriz plana $B$ (matriz que contiene el mensaje que se desea codificar).

c). **(0.4)** ¿Cuál es el mensaje que le envío Camilo a Lucía?


**NOTA:** Remitirse a la **Guía # 3** en la cual se explica el Método Hill.

In [3]:
# Solución ejercicio 2. (No olvide imprimir las respuestas de sus cálculos)

# Importar la biblioteca numpy con el alias np.
import numpy as np

# (a):

# Definir e imprimir las matrices A y C
key = [0, 0, 1, -1, 0, 0, 4, -1, 1, 2, -2, 4, 1, 1, 2, 2, -4, 0, 0, -2, 0, 2, -1, 1, 2]
A = np.array(key).reshape(5, 5)

coded_msg = [-9, 0 , -6, -8, 5, 15, 8, 4, 8, -23, 11, 12, 8, 3, -27, 7, -15, -1, 0, -6, 
             6, 161, 110, 84, 82, 69, -1, 84, 104, 38, 125, 157, 82, 94, 75, 73, 43, 135,
             105, 128, 26, 106, 143, 140, 56, 84, 77, 25, 102, 112, 38, 127, 175, 82, 104,
             75, 43, 29, 127, 103, 128, -16, 134, -128, -108, -22, -36, -64, 0, -68, -106, 10,
             -94, -158, -38, -70, -40, -14, 6, -110, -64, -72, 24, -84, 105, 76, 46, 64, 41, -7,
             66, 70, 20, 93, 101, 56, 62, 37, 71, 19, 79, 69, 84, 16, 50]

C = np.array(coded_msg).reshape(-1, 5).T

print("Matriz de codificación A (5x5):")
print(A)
print("\nMatriz codificada C (5xN):")
print(C)



Matriz de codificación A (5x5):
[[ 0  0  1 -1  0]
 [ 0  4 -1  1  2]
 [-2  4  1  1  2]
 [ 2 -4  0  0 -2]
 [ 0  2 -1  1  2]]

Matriz codificada C (5xN):
[[  -9   15   11    7    6   69  125   73   26   84   38   75  128  -22
  -106  -70  -64   76   66   56   79]
 [   0    8   12  -15  161   -1  157   43  106   77  127   43  -16  -36
    10  -40  -72   46   70   62   69]
 [  -6    4    8   -1  110   84   82  135  143   25  175   29  134  -64
   -94  -14   24   64   20   37   84]
 [  -8    8    3    0   84  104   94  105  140  102   82  127 -128    0
  -158    6  -84   41   93   71   16]
 [   5  -23  -27   -6   82   38   75  128   56  112  104  103 -108  -68
   -38 -110  105   -7  101   19   50]]


In [4]:
# Definir e imprimir la matriz B

# (b):

if np.linalg.det(A) != 0:
    A_inv = np.linalg.inv(A)
    B = np.dot(A_inv, C).round().astype(int)
    print("\nMatriz plana B (mensaje original codificado en bloques):")
    print(B)
else:
    print("\nLa matriz A no es invertible, no se puede descifrar el mensaje.")



Matriz plana B (mensaje original codificado en bloques):
[[  -8   16   13   -4  126   86  188  110  136  132  124  122   -8  -29
  -127  -52 -110   82  114   94   82]
 [  -2   16   20   -4   40  -20   41  -42   25  -18   12  -30   46   16
    24   35  -88   26  -16   22   10]
 [ -12   14   11    3  100  128  150  156  154  106  148  116   67  -43
  -179  -39  -62   90   90   82   90]
 [  -2   -2    0   -4   94   60   26   84  128   22  110   40  -61  -21
   -73   31    2   14   24   26   10]
 [   0  -20  -28    5    4   73   59  143   16  116   60  119  -36  -61
   -96 -125  109    8   99   16   55]]


In [5]:
# Mensaje que envío Camilo a Lucía

#(c):
print("\nMensaje descifrado (asumiendo letras mayúsculas A=0...Z=25):")
mensaje = ""
for valor in B.T.flatten():
    letra = chr((valor % 26) + ord('A'))
    mensaje += letra
print(mensaje)



Mensaje descifrado (asumiendo letras mayúsculas A=0...Z=25):
SYOYAQQOYGNULAYWWDWFWOWQEIGYIVGPUAHGKAGNGZYYQCICWMUMSGISWMOPSUPRQXQJFRDYDFIAJNFFUQQCFEAMOIKKMYVQWEAQEKMKD


### **Ejercicio #3: (0.6)**
Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 -k & k-1 & k+1 & k & 0\\
3 & 1 & 1 & 3 & -1\\
4-k & k & k+3 & -k & 1\\
-2 & 3 & 4 & 6 & 2\\
0 & 2 & 1 & 0 & 4
\end{pmatrix}.
\end{equation*} \


a). **(0.3)**  Halle los valores de $k$ para los cuales la matriz $A$ tiene inversa.

b). **(0.3)**  Halle los valores de $k$ para los cuales $\det(A) = 6+2k$.


In [7]:
# Solución Ejercicio 3. (No olvide imprimir las respuestas de sus cálculos)

# (a):
import sympy as sp

k = sp.Symbol('k', real=True)


A = sp.Matrix([
    [-k,    k-1,  k+1,  k,  0],
    [3,     1,    1,    3, -1],
    [4-k,   k,    k+3, -k,  1],
    [-2,    3,    4,    6,  2],
    [0,     2,    1,    0,  4]
])


det_A = A.det()
print("Determinante de A:")
print(det_A)


k_no_inversa = sp.solve(det_A, k) # Valores de k para los cuales A no tiene inversa i.e det(A) = 0

print("\n A tiene inversa para todo k excepto:")
for val in k_no_inversa:
    print(f"  k ≠ {val}")



Determinante de A:
-54*k**2 + 14*k + 216

 A tiene inversa para todo k excepto:
  k ≠ 7/54 - sqrt(11713)/54
  k ≠ 7/54 + sqrt(11713)/54


In [8]:
# Solución Ejercicio 3. (No olvide imprimir las respuestas de sus cálculos)

# (b):
equation = sp.Eq(det_A, 6 + 2*k)
k_solutions = sp.solve(equation, k)

print("\n(b) Valores de k para los cuales det(A) = 6 + 2k:")
print(k_solutions)




(b) Valores de k para los cuales det(A) = 6 + 2k:
[1/9 - 2*sqrt(79)/9, 1/9 + 2*sqrt(79)/9]



### **Ejercicio #4: (0.7)**
Sean $A(x_1,y_1), \ B(x_2,y_2)$ y $C(x_3,y_3)$ tres puntos en el plano $xy$. El área del triángulo formado por dichos puntos $A,B,C$ es dada por la expresión  

\begin{equation*}
 \mbox{Área} = \frac{1}{2} \left | \det
\begin{pmatrix}
x_1 & y_1 & 1\\
x_2 & y_2 & 1 \\
x_3 & y_3 & 1
\end{pmatrix} \right|,
\end{equation*}

donde el símbolo $|.|$ denota el valor absoluto.

a). **(0.3)** Sean $A(-5,-2), \ B(-7,7)$ y $C(9,2)$. Halle el área del triángulo formado por los puntos $A, \ B, \ C$.  

b). **(0.4)**  ¿Para qué valores de $k$ el **cuadrado del área del triángulo** formado por los puntos $A(-4,k), \ B(1,k)$ y $C(k,3)$ es igual a $100\ \mbox{cm}^4$?

In [9]:
# Solución Ejercicio 4. (No olvide imprimir las respuestas de sus cálculos)

# (a): 
import sympy as sp

x1, y1 = -5, -2
x2, y2 = -7, 7
x3, y3 = 9, 2


M = sp.Matrix([
    [x1, x2, x3],
    [y1, y2, y3],
    [ 1,  1,  1]
])


det_M = M.det()
print("Determinante del 3×3:", det_M)


area = sp.Abs(det_M) / 2
print("Área del triángulo:", area)




Determinante del 3×3: -134
Área del triángulo: 67


In [10]:
# Solución Ejercicio 4. (No olvide imprimir las respuestas de sus cálculos)

# (b):

import sympy as sp

k = sp.symbols('k', real=True)


area_b_squared = 25*(k - 7)**2/4
eq = sp.Eq(area_b_squared, 100)

solutions_k = sp.solve(eq, k)

print("Valores de k para los cuales el cuadrado del área es 100:")
print(solutions_k)



Valores de k para los cuales el cuadrado del área es 100:
[3, 11]


### **Ejercicio #5: (0.7)**
Considere el conjunto de vectores de $\mathbb{R}^6$:

$$ S = \{ (1, 1, 0, 1, 0, 0), (2, 1, 0, 2, 0, 1), (0, -1, -1, -1, 2, 0), (-1, 0, -1, -1, 1, -1),(0, -1, -2, 0, 1,0), (2,0,1,2, -2,2)\}.     $$

(a). **(0.3)** Muestre que dicho conjunto $S$ es una base para $\mathbb{R}^6$.

(b). **(0.4)** Determinar las coordenadas del vector $(-4, -2, 10,4,-1,-8)$ en dicha base.

In [11]:
# Solución Ejercicio 5. (No olvide imprimir las respuestas de sus cálculos)

# (a):
import sympy as sp

v1 = sp.Matrix([ 1,  0, -1,  0, -1,  0])
v2 = sp.Matrix([ 0,  1,  1,  0,  0,  0])
v3 = sp.Matrix([ 1,  0,  0, -1, -2,  0])
v4 = sp.Matrix([ 0,  1,  0, -1,  0,  1])
v5 = sp.Matrix([ 0,  0,  1,  1,  1, -1])
v6 = sp.Matrix([ 0,  1,  1, -1,  0,  1])


M = sp.Matrix.hstack(v1, v2, v3, v4, v5, v6)

det_M = sp.simplify(M.det())
print(det_M)

-1


In [12]:
# Solución Ejercicio 5. (No olvide imprimir las respuestas de sus cálculos)

# (b):
b = sp.Matrix([7, -3, 6, 1, 4, -5])
coords = M.LUsolve(b)


print("Coordenadas del vector (7, -3, 6, 1, 4, -5) en la base S:")
print(coords)


Coordenadas del vector (7, -3, 6, 1, 4, -5) en la base S:
Matrix([[3], [-13], [4], [3], [15], [7]])


### **Ejercicio #6: (1.0)**
Considere el conjunto

$$ V= \{ \textbf{u} = (u_1,u_2):  u_{1},u_{2} \in \mathbb{R} \}.$$

Para  $\textbf{u} = (u_1,u_2)$, $\textbf{w} = (w_1,w_2)$ en  $V$ y $\alpha \in \mathbb{R}$ se definen  las operaciones:

$$\textbf{u} \oplus \textbf{w} := (u_1 + w_1 + 2,u_2 + w_2 + 2),$$

$$ \alpha \odot \textbf{u} := (\alpha + \alpha u_1 -1,\alpha + \alpha u_2 -1).   $$

a). **(0.2)** Muestre que el elemento neutro aditivo es $\textbf{0} = (-2,-2)$,  verificando la igualdad $\textbf{0} \oplus (14,27) = (14,27).$

b). **(0.3)** Halle $  5 \odot [(-16,3)\oplus (18,-7)]. $

c).**(0.3)** Halle $  5 \odot (-16,3) \oplus 5 \odot (18,-7). $

d). **(0.2)** ¿Es $V$, con esas operaciones definidas, un espacio vectorial?


In [13]:
#########---------- Ejecutar esta parte antes de dar respuestas a las preguntas-----------#########

# NOTA: Las operaciones suma y producto aqui definidas pueden ser calculadas  mediante las siguientes funciones:

SUMA = lambda u,w:  np.array([[u[0,0] + w[0,0] + 2, u[0,1] + w[0,1] + 2]])

# La función SUMA recibe como entradas los elementos u,w y devuelve como resultado la suma según la definición.

PRODUCTO = lambda alpha,u:  np.array([[alpha + alpha*u[0,0] - 1, alpha + alpha*u[0,1] - 1]])

# La función PRODUCTO recibe como entradas un número real alpha y un elemento u de V, y da como resultado el producto por un escalar según la definición.

# Ejemplo: Hallemos la suma de u = (2,7) con w = (0,4).

u = np.array([[2, 7]])

w = np.array([[0, 4]])

Sol = SUMA(u,w)

print('Sol =', Sol)


Sol = [[ 4 13]]


In [15]:
# Solución Ejercicio 6. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas la función antes definida

# (a):
import numpy as np
SUMA = lambda u, w: np.array([[u[0,0] + w[0,0] + 2, u[0,1] + w[0,1] + 2]])
PRODUCTO = lambda alpha, u: np.array([[alpha + alpha*u[0,0] - 1, alpha + alpha*u[0,1] - 1]])


cero = np.array([[-2, -2]])
v = np.array([[14, 27]])
resultado_a = SUMA(cero, v)
print("0 ⊕ (14, 27) =", resultado_a)


0 ⊕ (14, 27) = [[14 27]]


In [22]:
# Solución Ejercicio 6. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas las funciones antes definida

# (b):
import numpy as np
SUMA = lambda u, w: np.array([[u[0,0] + w[0,0] + 2, u[0,1] + w[0,1] + 2]])
PRODUCTO = lambda alpha, u: np.array([[alpha + alpha*u[0,0] - 1, alpha + alpha*u[0,1] - 1]])


u = np.array([[-16, 3]])
w = np.array([[18, -7]])


suma_resultado = SUMA(u, w)
print("P1: (-16,3) ⊕ (18,-7) =", suma_resultado)


resultado_b = PRODUCTO(5, suma_resultado)
print("P2(Resultado): 5 ⊙ (-16,3) ⊕ (18,-7) =", resultado_b)


P1: (-16,3) ⊕ (18,-7) = [[ 4 -2]]
P2(Resultado): 5 ⊙ (-16,3) ⊕ (18,-7) = [[24 -6]]


In [18]:
# Solución Ejercicio 6. (No olvide imprimir las respuestas de sus cálculos)

# Debe usar en sus respuestas la función antes definida

# (c):
import numpy as np
SUMA = lambda u, w: np.array([[u[0,0] + w[0,0] + 2, u[0,1] + w[0,1] + 2]])
PRODUCTO = lambda alpha, u: np.array([[alpha + alpha*u[0,0] - 1, alpha + alpha*u[0,1] - 1]])


u = np.array([[-16, 3]])
w = np.array([[18, -7]])


prod1 = PRODUCTO(5, u)
print("Paso 1: 5 ⊙ (-16,3) =", prod1)

prod2 = PRODUCTO(5, w)
print("Paso 2: 5 ⊙ (18,-7) =", prod2)

resultado_c = SUMA(prod1, prod2)
print("Paso 3: Resultado final =", resultado_c)


Paso 1: 5 ⊙ (-16,3) = [[-76  19]]
Paso 2: 5 ⊙ (18,-7) = [[ 94 -31]]
Paso 3: Resultado final = [[ 20 -10]]


In [23]:
# Solución Ejercicio 6. (No olvide imprimir las respuestas de sus cálculos)

# (d):

resultado_b = np.array([[24, -6]])
resultado_c = np.array([[20, -10]])

distributiva_valida = np.array_equal(resultado_b, resultado_c)
print("¿Se cumple la distributividad del producto escalar respecto a la suma?")
print("Resultado (b):", resultado_b)
print("Resultado (c):", resultado_c)
print("¿Son iguales? ->", distributiva_valida)


if distributiva_valida:
    print("→ Podría ser un espacio vectorial.")
else:
    print("→ No es un espacio vectorial.")

¿Se cumple la distributividad del producto escalar respecto a la suma?
Resultado (b): [[24 -6]]
Resultado (c): [[ 20 -10]]
¿Son iguales? -> False
→ No es un espacio vectorial.
